### ISSUE TITLE
Redash should support TTL for result set expiration time

### ISSUE THREAD

**Issue by gaecoli** [RedashCommunity/redash#31]
If there is no expiration time for the result set, each update time needs to be refreshed. And the result set will be larger, resulting in larger storage space.

**Comment by justinclift** [comment]
For queries with a defined refresh schedule, I'm thinking the default TTL should probably match the refresh schedule.

It sounds like you're thinking of a different scenario though.  What's an example where a TTL for a query result would be useful, and does the refresh schedule interact with that in some way? :smile:

**Comment by gaecoli** [comment]
> For queries with a defined refresh schedule, I'm thinking the default TTL should probably match the refresh schedule.
> 
> It sounds like you're thinking of a different scenario though. What's an example where a TTL for a query result would be useful, and does the refresh schedule interact with that in some way? 😄

The data of the data source may change every day. For this scenario, it may be necessary to set an expiration time for the query. If the results exceed the expiration time, the data should be automatically refreshed. Now it is usually necessary to manually refresh to obtain the latest data. , I think it is a very bad experience.

For example, I set a TTL for the result set to expire in 24 hours, that is, one day, then the user will not see the expired results when they open redash the next day. This is very beneficial for use scenarios in enterprises.

**Comment by justinclift** [comment]
Ahhh, I think I understand now.  Are you meaning a TTL for the query result to be returned?

eg when you start a query, it should expire "at some point" if it doesn't return a result within that time

**Comment by gaecoli** [comment]
> Ahhh, I think I understand now. Are you meaning a TTL for the query result to be returned?
> 
> eg when you start a query, it should expire "at some point" if it doesn't return a result within that time

Yep!

**Comment by justinclift** [comment]
Cool.  Yeah, that sounds like a decent idea.  The backend already has a gunicorn timeout value, which we'd need to make sure doesn't conflict with it:

https://github.com/RedashCommunity/redash/blob/bb1d45ba3e1690a8acef192935916c2d6e5476d4/bin/docker-entrypoint#L48

We could probably get that value from the environment when the server starts up and use it as a default value to appear in the user interface.  But we could also allow for it to be changed via the front end so people can override it for specific queries.

Hmmm... it *might* be a bit complicated at first, due to needing the backend worker process to use that value.  So we'd probably need to stop using that environment variable to start the workers with.  Will probably need more thinking about. :smile:
